
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    image: wordpress
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    expose:
      - "3306"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/asangerm/data/mariadb'
      o: 'bind'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/asangerm/data/wordpress'
      o: 'bind'